a-sit-plus/vck

- .github/workflows/publish-pages-only.yml
- .github/workflows/publish.yml
- build.gradle.kts
- vclib-aries/build.gradle.kts
- vclib-openid/build.gradle.kts
- vclib/build.gradle.kts
also  fix condition for gitlab deps.
repository's "pages" setting needs to be set to "GitHub actions" (without selecting an action) for pages to work
> publish docs to pages

- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt
please test on the target branch, as I did not want to replicate the fixes to the test cases, since they were not cherry-pickable. hence I am directly assigning this to you, @nodh
> make cert optional in CryptoPublicKey

- .gitmodules
- conventions-vclib/src/main/kotlin/VcLibVersions.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
(needs some time  until KmmResult actually lands in maven central)
> use new KmmResult

- CHANGELOG.md
- conventions-vclib/src/main/kotlin/VcLibVersions.kt
- gradle.properties
- vclib-aries/src/commonMain/kotlin/at/asitplus/wallet/lib/msg/JwmAttachment.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/IssuerService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/InMemoryIssuerCredentialStore.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifierAgent.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseHeader.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseKey.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseSigned.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/DeviceRequest.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/MobileDrivingLicence.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/MobileSecurityObject.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/ByteArrayBase64Serializer.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/ByteArrayBase64UrlSerializer.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JsonWebKey.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JweEncrypted.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsSigned.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/MultibaseHelper.kt
Anything else apart from version bump?
> update vclib-specific dependencies

- vclib-openid/build.gradle.kts
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt
Adjust code to make it conform to previously existing api
> Fix: Thorough request object retrieval architecture

- CHANGELOG.md
- conventions-vclib/src/main/kotlin/VcLibConventions.kt
- conventions-vclib/src/main/kotlin/VcLibVersions.kt
- gradle.properties
also fixes the sign-publish task dependency
> update to latest conventions

- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Holder.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/InputEvaluator.kt
This will allow the wallet to delegate the evaluation of what is to be presented to the vclib
> Feature: Expose input descriptor matching to library users

- CHANGELOG.md
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServer.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerMetadata.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/SimpleAuthorizationService.kt
> Add OAuth2ServerMetadata

- build.gradle.kts
- conventions-vclib/build.gradle.kts
- vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciProcessTest.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt
- vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JweSerializationTest.kt
- vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JwkSerializationTest.kt
- vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JwsHeaderSerializationTest.kt
- vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
- vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
- vclib/src/jvmTest/kotlin/at/asitplus/wallet/lib/jws/JsonWebKeyJvmTest.kt
- vclib/src/jvmTest/kotlin/at/asitplus/wallet/lib/jws/JwsServiceJvmTest.kt
> Kmp crypto update

- vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopX509SanDnsTest.kt
- vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JwsHeaderSerializationTest.kt
- vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
> update to KMP-Crypto 3.1.0

- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
Diff may looks huge, but the single commits are rather small
> Refactor OIDC siop wallet

- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt
Refactors the SIOP verifier to improve readability.
> Refactor OIDC siop verifier

- .gitignore
- CHANGELOG.md
- README.md
- conventions-vclib/gradle/wrapper/gradle-wrapper.properties
- conventions-vclib/src/main/kotlin/VcLibVersions.kt
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- vclib-openid/build.gradle.kts
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/ZlibService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt
- vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/DefaultZlibService.kt
- vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
- vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/DefaultZlibService.kt
- vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
- Kotlin 2.0.0
- Gradle 8.8
- Bouncy Castle 1.78.1
- Kotest 5.9.0
- Ktor 2.3.11
- kotlinx.datetime 0.6.0
- kotlinx.coroutines 1.8.1
- KmmResult 1.6.0
- Serialization 1.7.1-SNAPSHOT
(uses unpublished KMP-Crypto for now)
> Kotlin 2.0.0 + Dependency Updates

- build.gradle.kts
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
- vclib/src/iosMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
- vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
Makes handling CryptoSignatures sane again (see [the corresponding KMP-Crypto PR](https://github.com/a-sit-plus/kmp-crypto/pull/84))
> Update to latest KMP-Crypto

- CHANGELOG.md
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequest.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationResponse.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Verifier.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/KeyBindingJws.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/SelectiveDisclosureItem.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/ClaimFormatEnum.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/InputEvaluator.kt
- vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/SdJwtSigned.kt
- vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/SdJwtSerializationTest.kt
- vclib/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/DefaultCryptoService.kt
Updates SIOP, SD-JWT implementation, refactors some methods
> Update SIOP, SD-JWT implementation

- CHANGELOG.md
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequest.kt
- vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequestParameterFromSerializerTest.kt
Adds serialization to the AuthenticationRequestParameter class.
> AuthenticationRequestParameterFrom De-/Serializer

- .github/workflows/test-jvm.yml
- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/IssuerMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenRequestParameters.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsContentTypeConstants.kt
I'm also thinking about extracting that token functionality from `WalletService`, but this would be better suited in a future PR.
> OAuth DPoP

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/AuthorizationDetails.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/BatchCredentialIssuanceMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialFormatEnum.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialOffer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestParameters.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestProof.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestProofContainer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/IssuerMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OAuth2AuthorizationServerMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenRequestParameters.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/NonceService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/SimpleAuthorizationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/DeserializationTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciInteropTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciProcessTest.kt
Update our implementation of https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html to Draft 14
> OpenId4VCI Draft 14

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/AuthorizationDetails.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciCodeFlowTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciInteropTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciPreAuthTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciProcessTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/SerializationTest.kt
Fixes #145 by clarifying and testing `credential_identifiers`.
> Update OID4VCI implementation

- CHANGELOG.md
- dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/FormatContainerJwt.kt
- dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/FormatHolder.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/PresentationFactory.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorSdJwtBindingTest.kt
> Verification of Confirmation Key

- .gitignore
- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/JwtVcIssuerMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequestParameterFromSerializerTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopSdJwtProtocolTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWalletScopeSupportTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OpenId4VpInteropTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Holder.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Parser.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Verifier.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifierAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/VcDataModelConstants.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsContentTypeConstants.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentComplexSdJwtTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentRevocationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentSdJwtTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVcTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVpTest.kt
- vck/src/jvmMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.jvm.kt
Add interop tests for the Piloting Definition Scope from POTENTIAL, refactoring the handling of identifiers and keyIds along the way
> POTENTIAL Piloting Definition Scope

- CHANGELOG.md
- conventions-vclib/src/main/resources/vcLibVersions.properties
- gradle.properties
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/DeviceSignedItemSerializationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/IssuerSignedItemSerializationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/Tag24SerializationTest.kt
- vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceJvmTest.kt
Fixes COSE signature verification as the comment in https://github.com/a-sit-plus/vck/issues/72#issuecomment-2539774230 uncovered.
see also https://github.com/a-sit-plus/signum/pull/223
> COSE: Read raw payload for signature verification

- .github/workflows/test-ios.yml
- .github/workflows/test-jvm.yml
- .gitmodules
- CHANGELOG.md
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/DeviceSignedList.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/NamespacedDeviceNameSpacesSerializer.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/Iso18013SpecTest.kt
> ISO: Fix serialization of device signed items

- vck-openid-ktor/build.gradle.kts
- vck-openid-ktor/src/commonTest/kotlin/KotestConfig.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWalletTest.kt
Adds tests for our ktor-based clients, used in the App Wallet.
Suggesting to squash & merge.
> Tests for ktor clients

- conventions-vclib/src/main/resources/vcLibVersions.properties
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWalletTest.kt
Fixed KLIB resolver dependency resolution bug
> Update to latest EU PID credential

- build.gradle.kts
> copy over EU flag to API docs assets

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/data/NonEmptyList.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/data/collections/NonEmptyList.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/data/validation/third_party/kotlin/String.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/data/validation/third_party/kotlin/collections/Collection.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/data/validation/third_party/kotlin/collections/Iterable.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsPathPointer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsPathPointerInlineSerializer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsPathPointerSegment.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsQueryIdentifier.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsQueryList.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsQueryResult.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialQueryIdentifier.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialQueryInstance.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialQueryList.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialQueryMatchingResult.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialSetQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLCredentialSetQueryPurpose.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLIsoMdocClaimsQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLIsoMdocCredentialQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLSdJwtCredentialQuery.kt
- openid-data-classes/src/commonTest/kotlin/at/asitplus/openid/dcql/DCQLClaimsPathPointerTest.kt
- openid-data-classes/src/commonTest/kotlin/at/asitplus/openid/dcql/DCQLCredentialQueryTest.kt
- openid-data-classes/src/commonTest/kotlin/at/asitplus/openid/dcql/DCQLQueryTest.kt
- openid-data-classes/src/commonTest/kotlin/at/asitplus/openid/dcql/DCQLSdJwtCredentialQueryTest.kt
Separate refactor to reduce size of final merge request for incorporation of DCQL queries
> Refactor DCQL implementation before final incorporation

- .github/workflows/build-ios.yml
- .github/workflows/build-jvm.yml
- .github/workflows/publish.yml
- CHANGELOG.md
- gradle.properties
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/ResponseParametersFrom.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpIsoProtocolTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpX509SanDnsTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/SessionTranscript.kt
- ISO: Fix serialization of device authentication bytes
- ISO: Fix generating `mdocGeneratedNonce` for device authentication acc. to ISO 18013-7
- OpenID4VP: Support extracting authentication response from JWS inside JWE
> Release 5.3.3

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/ResponseParametersFrom.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpIsoProtocolTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpX509SanDnsTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/X509CertificateExtension.kt
Consolidates changes from Warsaw interop event, that have been deployed in 5.3.2 and 5.3.3
> OpenID4VP improvements

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/ResponseParametersFrom.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpIsoProtocolTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpX509SanDnsTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/KeyMaterial.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/X509CertificateExtension.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/IssuerSignedItemSerializer.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/IssuerSignedList.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/SessionTranscript.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/ValueDigest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/IssuerSignedItemSerializationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt
Consolidates changes from Warsaw interop event, that have been deployed in 5.3.2 and 5.3.3
> ISO mdoc improvements

- CHANGELOG.md
- conventions-vclib/src/main/resources/vcLibVersions.properties
@JesusMcCloud  Is there anything more to do, e.g. for Key Agreement?
> Signum 3.14.0

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestProof.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestProofContainer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestProofSupported.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/KeyAttestationRequired.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/SupportedCredentialFormat.kt
- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClient.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/AuthorizationServiceStrategy.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/IssuedAccessToken.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/IssuedCode.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2Client.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialAuthorizationServiceStrategy.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerAdapter.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2SecurityExtensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/SerializerSketch.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientAuthenticationTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciAttestationTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciCodeFlowTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciPreAuthTest.kt
Resolves https://github.com/a-sit-plus/vck/issues/152
> OAuth2 improvements

- CHANGELOG.md
- openid-data-classes/build.gradle.kts
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/ClientNonceResponse.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialRequestParameters.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/CredentialResponseEncryption.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/IssuerMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenResponseParameters.kt
- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClient.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/TokenService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerAdapter.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciAttestationTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciCodeFlowTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciEncryptionTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciPreAuthTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/SerializationTest.kt
Implement client nonces the correct way (not in the token response), and support encryption of issued credentials.
> OpenID4VCI: Nonces and Encryption

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenRequestParameters.kt
- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClient.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/ClientAuthRequest.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2Client.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/TokenService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientDPoPTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciCodeFlowTest.kt
- vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolder.kt
- vck-rqes/src/commonTest/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolderTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsContentTypeConstants.kt
Follows recommendation to use refresh tokens from https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-1_0.html#name-token-endpoint
> OAuth2: Refresh tokens

- README.md
> update usage in readme

- CHANGELOG.md
- rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/collection_entries/TransactionData.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestOptions.kt
> Rrequest options credential

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/AuthenticationRequestParameters.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestOptions.kt
As discussed per mail, makes sense to remove SIOP-related parameters
> SIOP vs OpenId4VP

- CHANGELOG.md
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2Client.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientTest.kt
- vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolder.kt
> OAuth2: Optional PAR

- vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolder.kt
Fixes #262 and improves error responses
> Fix erroneous requirement check

- CHANGELOG.md
- dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/DifInputDescriptor.kt
- dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/InputDescriptor.kt
- rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/QesInputDescriptor.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/PresentationSubmissionValidator.kt
Fixes parsing authn requests from [Animo](https://funke.animo.id/)
> OID4VP: Temp. fix to parse input descriptors with group

- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpVerifier.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/StatusListTokenIntegrityValidator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/StatusListToken.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentRevocationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt
- vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceJvmTest.kt
Part 2, after https://github.com/a-sit-plus/vck/pull/256
> COSE Function Composition

- CHANGELOG.md
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpIsoProtocolTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/PresentationDataClasses.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt
Fixes presentation of PID + mDoc against https://rp-playground-ingroupe.utoconnect.com/
> Fix mdoc presentation multiple documents

- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpHolder.kt
Otherwise it fails because no polymorphic serializer is registered for `InputDescriptor`.
@n0900 Please have a look at other classes where this might be the case.
> Fix deserialization of presentation definition

- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/StatusListTokenIntegrityValidator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/MediaTypes.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/StatusListToken.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/rfc/tokenStatusList/MediaTypes.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/rfc/tokenStatusList/third_party/kotlin/Boolean.kt
See https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-08.html#section-5.1-3.1.1:
The following content applies to the JWT Header:
* `typ`: REQUIRED. The JWT type MUST be `statuslist+jwt`.
> Fix JWT type of status list token

- CHANGELOG.md
- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWallet.kt
- vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWalletTest.kt
Needed for https://github.com/a-sit-plus/valera/pull/226
> OID4VP: Let client decide whether to open redirected URL

- CHANGELOG.md
- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWallet.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpHolder.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentComplexSdJwtTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentRevocationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentSdJwtTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/StoreEntrySerializationTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorMdocTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVcTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVpTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt
- vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceJvmTest.kt
> Functions: COSE

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsPathPointer.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLClaimsQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLIsoMdocClaimsQuery.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/dcql/DCQLJsonClaimsQuery.kt
- openid-data-classes/src/commonTest/kotlin/at/asitplus/openid/dcql/DCQLIsoMdocClaimsQueryTest.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestOptions.kt
Just a quick fix to parse requests from https://funke.animo.id/
> DCQL: Quick fix for new claim query format

- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
Refactors away the secondary constructors
> Refactor initialization of Validator

- CHANGELOG.md
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthnResponseResult.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Verifier.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/validation/TokenStatusResolver.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/validation/TokenStatusValidationResult.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/validation/TokenStatusValidator.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/IsoDocumentParsed.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/VcJwsVerificationResultWrapper.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/rfc/tokenStatusList/primitives/TokenStatusValidationResult.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentSdJwtTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorMdocTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVcTest.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVpTest.kt
Also allows library client to define acceptable token statuses
> Add explicit token status validation result

- CHANGELOG.md
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/LocalDateOrInstant.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/IssuerSignedItemSerializationTest.kt
Might be used by credential implementations, e.g. EU PID
> LocalDateOrInstant

- vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClient.kt
> Fallback Scheme Fix Fix

- gradle.properties
- settings.gradle.kts
> cleanup composite build

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/RelyingPartyMetadata.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/wallet/lib/data/SelectiveDisclosureItemSerializer.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2SecurityExtensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciAttestationTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/JarmTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpEuRefInteropTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpInteropTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpX509HashTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpX509SanDnsTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/PreRegisteredClientTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/RedirectUriClientTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/VerifierAttestationTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsContentTypeConstants.kt
Implements correct behaviour for encrypted responses in OpenID4VP 1.0
Rebased from https://github.com/a-sit-plus/vck/pull/306
> OpenID4VP 1.0 Encrypted Responses

- CHANGELOG.md
- openid-data-classes/src/commonMain/kotlin/at/asitplus/dcapi/DCAPIHandover.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/dcapi/EncryptedResponse.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/dcapi/OID4VPHandover.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/dcapi/OpenID4VPDCAPIHandoverInfo.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/DeviceAuthentication.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/EncryptionInfo.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/OpenId4VpHandover.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/OpenId4VpHandoverInfo.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/SessionTranscript.kt
- openid-data-classes/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/SdJwtSigned.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/TokenVerificationService.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthenticationResponseFactory.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/AuthorizationRequestValidator.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpHolder.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt
- vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpIsoProtocolTest.kt
- vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/PresentationFactoryTest.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/PresentationDataClasses.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/ValidatorMdoc.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/ValidatorSdJwt.kt
- vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt
- vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/SessionTranscriptTest.kt
Use handover and session transcript definitions from [OpenID4VP 1.0](https://openid.net/specs/openid-4-verifiable-presentations-1_0-final.html#name-handover-and-sessiontranscr)
> OpenID4VP 1.0 Session Transcript
