a-sit-plus/vck

vclib-aries/build.gradle.kts, vclib-openid/build.gradle.kts, vclib/build.gradle.kts
please verify locally that it works by invoking `./gradlew clean dokkaHtmlMultiModule` and then navigating around a bit:
Html Doc:
Result after clicking on "(source)":
=> add source links to docs

vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/TestCredentialScheme.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/AtomicAttribute2023.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/CredentialSubject.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/RevocationListSubject.kt, vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/data/CredentialSubjectTest.kt
This greatly reduces implementors' constructor boilerplate by allowing them to have a main constructor only.
=> Make CredentialSubject abstract

CHANGELOG.md, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopIsoProtocolTest.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopSdJwtProtocolTest.kt
In order to not having to instantitate an `OidcSiopVerifier` for every `credentialRepresentation` we can move it from a class parameter to a function parameter
=> Moved credentialRepresentation from parameter to function

.github/workflows/mirror.yml
This PR adds the mirroring action to this repo.
Please do check if more files should be pruned before we merge this into main. E. g. do we really want to build it and consume minutes on a mac runner. isn't testing enough?
Also: check the repository settings for the variables used in the action
=> add mirroring action

.github/workflows/mirror.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml, CHANGELOG.md, DEVELOPMENT.md, README.md, build.gradle.kts, conventions-vclib/build.gradle.kts, conventions-vclib/settings.gradle.kts, conventions-vclib/src/main/kotlin/VcLibConventions.kt, conventions-vclib/src/main/kotlin/VcLibVersions.kt, gradle.properties, settings.gradle.kts, vclib-aries/build.gradle.kts, vclib-openid/build.gradle.kts, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt, vclib/build.gradle.kts, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt, vclib/src/jvmTest/kotlin/at/asitplus/wallet/lib/jws/JsonWebKeyJvmTest.kt
- Kotlin 1.9.23 inclduing workaround for KT-65315
- Update to latest KMP Crypto 2.5.0
- Fix: Add missing iOS exports
=> Update to Kotlin 1.9.23 and latest KMP-Crypto

vclib-openid/build.gradle.kts, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequestParameters.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopInteropTest.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt
Improved algorithm for retrieving AuthenticationResponseParameters as asked for in https://github.com/a-sit-plus/compose-wallet-app/pull/61#discussion_r1534006344
=> Thorough request object retrieval algorithm

conventions-vclib/src/main/kotlin/VcLibVersions.kt
Bumping dependency version of: 
- jsonpath
Issue first observed in: https://github.com/a-sit-plus/kmm-vc-library/pull/53#issuecomment-2109983034
=> Bump: Dependencies

vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/AttributeIndex.kt
This will be handy for the Wallet because the doctype is encoded into the id of input descriptors
=> Add credential scheme resolution by iso doctype

CHANGELOG.md, conventions-vclib/src/main/kotlin/VcLibVersions.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Holder.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/SubjectCredentialStore.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/InputEvaluator.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/PresentationSubmissionValidator.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/SubmissionRequirement.kt, vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/ValidatorVpTest.kt, vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/data/SubmissionRequirementsTest.kt
- `Holder.matchInputDescriptorsAgainstCredentialStore` now yields much richer details on credential matches.
- list of credentials that match an input descriptor, and for each constraint field also a list of fields matching that constraint field 
- Added `SubmissionRequirement.evaluate` to allow for verification of submission requirements
- Added second method for creating a presentation, where the user may present manually selected credentials and where the submission requirements are not checked.
=> Add: Improved presentation flexibility in holder

CHANGELOG.md, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/AuthenticationRequestParser.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/AuthenticationResponseFactory.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/AuthorizationRequestValidator.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/AuthorizationResponsePreparationState.kt, vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/PresentationFactory.kt, vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopCombinedProtocolTwoStepTest.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Holder.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt, vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/PresentationSubmissionValidator.kt
Separates the response building into two phases, allowing the user of the library to select credentials and attributes to be disclosed, but leaves the original logic in tact using default submissions
- Change `OidcSiopWallet`: 
- Add `startAuthorizationResponsePreparation`: Gathers data necessary for presentation building and yields a `AuthorizationResponsePreparationState`
- Add `finalizeAuthorizationResponseParameters`: Returns what `createAuthenticationParams` returned before, but also takes in `AuthorizationResponsePreparationState` and an optional non-default submission
- Add `finalizeAuthorizationResponse`: Returns what `createAuthenticationResponse` did before 
- Add `AuthorizationResponsePreparationState`: Holds data necessary for presentation building
- Add …
=> Separate authentication response building steps in SiopWallet

conventions-vclib/build.gradle.kts, conventions-vclib/settings.gradle.kts, conventions-vclib/src/main/kotlin/VcLibConventions.kt, conventions-vclib/src/main/kotlin/VcLibVersions.kt, conventions-vclib/src/main/resources/vcLibVersions.properties, settings.gradle.kts, vclib-aries/build.gradle.kts, vclib-openid/build.gradle.kts, vclib/build.gradle.kts
If Dr. Frankenstein was McGyver's apprentice… uses the kmp-crypto version catalog to avoid version mismatches.
directly targeting main for an xcframework release
=> apply kmp-crypto version catalog

vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/AttributeIndex.kt
It is very useful to be able to know which CredentialSchemes are registered. This makes the getter public but the setter remains private.
=> Make schemeSet readable

vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/AttributeIndex.kt
Admittetly even more permissive than before this function now also returns the associated representation and thus extending its use cases.
=> Add credential matching functionality

conventions-vclib/src/main/resources/vcLibVersions.properties, settings.gradle.kts, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopInteropTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopX509SanDnsTest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt, vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/jws/JsonWebKeyJvmTest.kt
=> update to lastest signum snapshot

CHANGELOG.md, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OAuth2AuthorizationServerMetadata.kt, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/SupportedCredentialFormatDefinition.kt, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenRequestParameters.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/AuthorizationServiceStrategy.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2Client.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/AuthenticationResponseFactory.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialAuthorizationServiceStrategy.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerAdapter.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2DataProvider.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/SimpleAuthorizationService.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/DummyOAuth2IssuerCredentialDataProvider.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciInteropTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciProcessTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/SerializationTest.kt
While working on https://github.com/a-sit-plus/vck/pull/130 it appeared to me we should extract more logic from OAuth 2.0 to decouple it from issuing, which should help with the ongoing work in https://github.com/a-sit-plus/vck/pull/127
=> Extract OAuth 2.0 functionality

CHANGELOG.md, dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/PresentationDefinition.kt, vck-aries/src/commonMain/kotlin/at/asitplus/wallet/lib/aries/PresentProofProtocol.kt, vck-aries/src/commonTest/kotlin/at/asitplus/wallet/lib/aries/DummyCredentialDataProvider.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/helper/PresentationFactory.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/AuthenticationRequestParameterFromSerializerTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/DummyCredentialDataProvider.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/DummyOAuth2IssuerCredentialDataProvider.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopCombinedProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopCombinedProtocolTwoStepTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopInteropTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopIsoProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopSdJwtProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWalletScopeSupportTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopX509SanDnsTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciProcessTest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/ConstantIndex.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/CredentialToJsonConverter.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/SelectiveDisclosureItem.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/dif/InputEvaluator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/SelectiveDisclosureItemSerializer.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentSdJwtTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/DummyCredentialDataProvider.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/SdJwtSerializationTest.kt
Now it works, just leave the deserialization up to implementers.
=> Fix serialization of byte arrays in SD-JWT

CHANGELOG.md, conventions-vclib/src/main/resources/vcLibVersions.properties, dif-data-classes/build.gradle.kts, openid-data-classes/build.gradle.kts, vck-aries/build.gradle.kts, vck-openid/build.gradle.kts, vck/build.gradle.kts
Update to JsonPath4K 2.4.0 to be able to auto-export all transitive dependencies to an XCF that actually works.
Bottom line: bloats the XFC but cleans dependency declaration
=> Fix XCF export

CHANGELOG.md, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopVerifier.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopCombinedProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopIsoProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopSdJwtProtocolTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopX509SanDnsTest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/SubjectCredentialStore.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Verifier.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/data/VerifiableCredentialSdJwt.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/ReconstructedSdJwtClaims.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/SdJwtSigned.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/AgentSdJwtTest.kt
Part 1 of a series of MR to handle complex SD-JWT, as discussed in #20, but without `kotlinx.serialization`.
This PR prepares the public API of this library to be able to handle complex SD-JWT structures.
=> SD-JWT: Refactor interface

CHANGELOG.md, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/DeviceAuth.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/DeviceSigned.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/DocRequest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/IssuerSigned.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/MobileSecurityObject.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/DeviceSignedItemSerializationTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/IssuerSignedItemSerializationTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/Tag24SerializationTest.kt
Uses type parameter from `CoseSigned` to clarify usages of the payload (and reduce the number of manual tagging payloads).
See also https://github.com/a-sit-plus/signum/pull/194
=> COSE Signed API

vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifiablePresentationFactory.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/agent/SdJwtVerificationTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/DeviceSignedItemSerializationTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/IssuerSignedItemSerializationTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/Tag24SerializationTest.kt, vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceJvmTest.kt
Builds upon https://github.com/a-sit-plus/signum/pull/209, but still requires some work
=> Improve Cose Signed types 

vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesWalletService.kt
Allows `RqesWalletService` to pass `stateToCodeStore` to Oauth2 client directly
=> Allows RqesWalletService to pass stateToCodeStore

vck-openid/build.gradle.kts
This removes the arrow dependency for good.
- We still need to update and release all credentials to use this VC-K version once released
- Then we need pull those updated credentials into Valera (or wherever we use them)
- Finally, our Valera build issues will also be resolved for good.
=> prepare proper removal of arrow

openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TokenResponseParameters.kt
According to RFC 6749 `expires_in` is only a RECOMMENDED parameter and as such can be null
=> Make expires nullable

vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolder.kt, vck-rqes/src/commonTest/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolderTest.kt
According to CSC Api we cannot use "credential"-scope AND the authenticationDetails.
In UC5 it was agreed on to use authentication data.
=> Fix createCredentialAuthenticationRequest

vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestParser.kt
This when became unnessesary when we changed the output to `RequestParametersFrom`
=> Remove unnessesary when

rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/SignatureResponse.kt, vck-rqes/src/commonMain/kotlin/at/asitplus/wallet/lib/rqes/RqesOpenId4VpHolder.kt
- Make `reponseId` optional
- Add `documentLocation` to `getCscAuthenticationDetails` and `createAuthRequest`
=> Enable atrust signing

CHANGELOG.md, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt, vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2Client.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/Extensions.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerAdapter.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2SecurityExtensions.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/SerializerSketch.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/ResponseParser.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientAuthenticationTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientTest.kt
As required by [OpenID4VC HAIP](https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-1_0.html) and defined in [OAuth 2.0 Attestation-Based Client Authentication](https://www.ietf.org/archive/id/draft-ietf-oauth-attestation-based-client-auth-05.html), add client authentication to the OAuth2 endpoints.
Details (e.g. where to get the `nonce` for the PoP JWT) are not sketched out in the drafts, so we skip that too.
=> Add Wallet Attestations

CHANGELOG.md, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/OpenIdConstants.kt, vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClient.kt, vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oauth2/SimpleAuthorizationService.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialIssuer.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2AuthorizationServerAdapter.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/OAuth2SecurityExtensions.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oauth2/OAuth2ClientDPoPTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciAttestationTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciCodeFlowTest.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidvci/OidvciPreAuthTest.kt
Implements sender-constrained access tokens as defined in [OAuth 2.0 Demonstrating Proof of Possession (DPoP)](https://datatracker.ietf.org/doc/html/rfc9449), mandated by [OpenID4VC HAIP](https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-1_0.html)
=> OAuth2: DPoP

rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/QesInputDescriptor.kt, rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/collection_entries/RqesDocumentDigest.kt, rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/collection_entries/TransactionData.kt
Requirements in the definition of `documentLocationUri` contradict themselves - should not force `hash`-parameter to be present
=> Remove incorrect requirement

CHANGELOG.md, vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWallet.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestOptions.kt
Corresponding changes to imports are because of moving to default IDEA import formatting policy
=> Fix: Remove parameter restriction on OpenId4VpWallet

CHANGELOG.md, vck-openid-ktor/src/commonMain/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VpWallet.kt
Fixes issues with e.g. [MATTR Verifier](https://tools.mattrlabs.com/mdoc-online-presentation)
=> OpenID4VP: Set exact content type for authentication responses

CHANGELOG.md, dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/BaseInputDescriptorSerializer.kt, dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/Json.kt, dif-data-classes/src/commonMain/kotlin/at/asitplus/dif/PresentationDefinition.kt, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/Json.kt, rqes-data-classes/src/commonMain/kotlin/at/asitplus/rqes/Json.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/AuthenticationRequestParameterFromSerializerTest.kt, vck-rqes/src/commonTest/kotlin/at/asitplus/wallet/lib/rqes/RqesRequestOptionsTest.kt, vck-rqes/src/commonTest/kotlin/at/asitplus/wallet/lib/rqes/TransactionDataInterop.kt
Issue:
In bigger structures, when the specific class was known, kotlinx.serialization would pick the generic polymorphic serializer for `InputDescriptor` instead of the specific `InputDescriptorSerializer` which is defined for the interface. In this case the `type` discriminator was added.
Solution:
To address this we force the serializer to use the contextual serializer instead which we set to the appropriate `InputDescriptorSerializer`.
To this end we also add a `BaseInputDescriptorSerializer` which only calls the `DifInputDescriptor` serializer without adding the type discriminator.
We need contextual serialization because `InputDescriptor` as an interface allows for open polymorphism and in our use case specifically `QesInputDescriptor` is not defined in the DIF artifact which means …
=> Fix erroneous encoding via contextual serialization

CHANGELOG.md, vck-openid-ktor/src/commonTest/kotlin/at/asitplus/wallet/lib/ktor/openid/OpenId4VciClientTest.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/CredentialAuthorizationServiceStrategy.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/PresentationFactory.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/VerifierAttestationTest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/CryptoService.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/IssuerAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/StatusListTokenIntegrityValidator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Validator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/Verifier.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/VerifierAgent.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/validation/mdoc/MdocInputValidator.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/cbor/CoseService.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/jws/JwsService.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/iso/IsoProcessTest.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JwsServiceTest.kt, vck/src/jvmTest/kotlin/at/asitplus/wallet/lib/cbor/CoseServiceJvmTest.kt
As suggested by @acrusage-iaik, `fun interface` provides advantages over the previously used `typealias`, e.g. named parameters for invocation as well as strict type checking (i.e. passing a function with the same signature is not enough, as has happened with `SignCoseFun` and `SignCoseDetachedFun`).
=> Fun interfaces

CHANGELOG.md, gradle.properties, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpVerifier.kt, vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/openid/RequestOptions.kt, vck-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/openid/OpenId4VpComplexSdJwtProtocolTest.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/agent/HolderAgent.kt
Improves interop with partners tested against in Vilnius:
- Generate `vct` field constraints as `const`
- Use JSON Path dot notation where possible
- Treat all requested attributes as optional and let the user select them
=> Improvements from Vilnius Interop Event

CHANGELOG.md, conventions-vclib/src/main/kotlin/VcLibConventions.kt, conventions-vclib/src/main/resources/vcLibVersions.properties, openid-data-classes/src/commonMain/kotlin/at/asitplus/iso/cborSerializer.kt, openid-data-classes/src/commonMain/kotlin/at/asitplus/openid/TransactionData.kt, vck/src/commonMain/kotlin/at/asitplus/wallet/lib/iso/cborSerializer.kt, vck/src/commonTest/kotlin/at/asitplus/wallet/lib/jws/JwsHeaderSerializationTest.kt
Fix erroneously url-encoding certificates in JWS headers.  
This should make it into a 5.7.1 release
=> Fix JWS cert encoding
